//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMvC.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speler
    {
        public Speler()
        {
            this.StatsTeam = new HashSet<StatsTeam>();
        }
    
        public int Id { get; set; }
        public string naam { get; set; }
        public string flag { get; set; }
        public Nullable<int> score { get; set; }
        public string platform { get; set; }
    
        public virtual ICollection<StatsTeam> StatsTeam { get; set; }
    }
}
