//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMvC.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsTeam
    {
        public int id { get; set; }
        public Nullable<int> speler_id { get; set; }
        public Nullable<int> extended_id { get; set; }
        public Nullable<double> goals_per_game { get; set; }
        public Nullable<double> goals_against_per_game { get; set; }
        public Nullable<double> goal_ratio { get; set; }
        public string favorit_team { get; set; }
        public string scored_most_with { get; set; }
        public string most_hated_player { get; set; }
        public string most_played_against { get; set; }
        public Nullable<int> seasons_played { get; set; }
        public Nullable<int> seasons_played_current_division { get; set; }
        public Nullable<int> highest_division { get; set; }
        public Nullable<int> relegations { get; set; }
    
        public virtual Speler Speler { get; set; }
        public virtual StatsTeamExtended StatsTeamExtended { get; set; }
    }
}
