//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMvC.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsTeamExtended
    {
        public StatsTeamExtended()
        {
            this.StatsTeam = new HashSet<StatsTeam>();
        }
    
        public int spelerId { get; set; }
        public Nullable<int> SeasonTeam { get; set; }
        public Nullable<int> WinsTeam { get; set; }
        public Nullable<int> LosesTeam { get; set; }
        public Nullable<int> DrawsTeam { get; set; }
        public Nullable<int> points { get; set; }
    
        public virtual ICollection<StatsTeam> StatsTeam { get; set; }
    }
}
